# Generated by Django 4.2.14 on 2024-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_tsc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachers_id',
            field=models.IntegerField(null=True),
        ),
    ]
