# Generated by Django 4.2.14 on 2024-09-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
    ]
