# Generated by Django 4.2.14 on 2024-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_module_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
